# Generated by Django 3.1.3 on 2020-11-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0021_auto_20201118_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='misdatos',
            name='region',
            field=models.CharField(blank=True, choices=[('I', 'Arica y Parinacota y Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama y Coquimbo'), ('IV', 'Valparaíso'), ('V', 'O Higgins'), ('VI', 'Maule'), ('VII', 'Ñuble, Biobío y La Araucanía (norte)'), ('VIII', 'La Araucanía (sur)'), ('IX', 'Los Ríos y Los Lagos(norte)'), ('X', '    Los Lagos(Sur) y Aysén'), ('XI', 'Magallanes'), ('RM', 'Metropolitana de Santiago')], default='RM', help_text='Seleccione una región', max_length=4),
        ),
    ]
