# Generated by Django 3.1.3 on 2020-11-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0022_misdatos_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Misdatos',
        ),
    ]
