# Generated by Django 3.1.2 on 2020-11-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='id_orden',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
