# Generated by Django 3.1.2 on 2020-11-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_id_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='id_orden',
        ),
    ]
