# Generated by Django 3.1.3 on 2020-11-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_remove_orden_id_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='orden',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
