# Generated by Django 3.1.3 on 2020-11-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_orden_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='orden',
        ),
    ]
