# Generated by Django 3.1.3 on 2020-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_remove_orden_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
