# Generated by Django 3.1.3 on 2020-11-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_orderline_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='nombre',
        ),
    ]
